/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { ScreenshothisError } from "./screenshothiserror.js";

/**
 * Service is not alive
 */
export type NotAliveErrorData = {
  status: operations.StatusNotAlive;
  timestamp: string;
  error: string;
};

/**
 * Service is not alive
 */
export class NotAliveError extends ScreenshothisError {
  status: operations.StatusNotAlive;
  timestamp: string;
  error: string;

  /** The original data that was passed to this error instance. */
  data$: NotAliveErrorData;

  constructor(
    err: NotAliveErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.timestamp = err.timestamp;
    this.error = err.error;

    this.name = "NotAliveError";
  }
}

/** @internal */
export const NotAliveError$inboundSchema: z.ZodType<
  NotAliveError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: operations.StatusNotAlive$inboundSchema,
  timestamp: z.string(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new NotAliveError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type NotAliveError$Outbound = {
  status: string;
  timestamp: string;
  error: string;
};

/** @internal */
export const NotAliveError$outboundSchema: z.ZodType<
  NotAliveError$Outbound,
  z.ZodTypeDef,
  NotAliveError
> = z.instanceof(NotAliveError)
  .transform(v => v.data$)
  .pipe(z.object({
    status: operations.StatusNotAlive$outboundSchema,
    timestamp: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotAliveError$ {
  /** @deprecated use `NotAliveError$inboundSchema` instead. */
  export const inboundSchema = NotAliveError$inboundSchema;
  /** @deprecated use `NotAliveError$outboundSchema` instead. */
  export const outboundSchema = NotAliveError$outboundSchema;
  /** @deprecated use `NotAliveError$Outbound` instead. */
  export type Outbound = NotAliveError$Outbound;
}
