/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGet } from "../funcs/healthGet.js";
import { healthGetLive } from "../funcs/healthGetLive.js";
import { healthGetReady } from "../funcs/healthGetReady.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  async get(
    options?: RequestOptions,
  ): Promise<models.HealthCheck> {
    return unwrapAsync(healthGet(
      this,
      options,
    ));
  }

  async getReady(
    options?: RequestOptions,
  ): Promise<operations.GetHealthReadyResponse> {
    return unwrapAsync(healthGetReady(
      this,
      options,
    ));
  }

  async getLive(
    options?: RequestOptions,
  ): Promise<operations.GetHealthLiveResponse> {
    return unwrapAsync(healthGetLive(
      this,
      options,
    ));
  }
}
