/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { screenshotsTake, TakeAcceptEnum } from "../funcs/screenshotsTake.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { TakeAcceptEnum } from "../funcs/screenshotsTake.js";

export class Screenshots extends ClientSDK {
  async take(
    request: operations.GetV1ScreenshotsTakeRequest,
    options?: RequestOptions & { acceptHeaderOverride?: TakeAcceptEnum },
  ): Promise<operations.GetV1ScreenshotsTakeResponse | undefined> {
    return unwrapAsync(screenshotsTake(
      this,
      request,
      options,
    ));
  }
}
