/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { screenshotsTake, TakeAcceptEnum } from "../funcs/screenshotsTake.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { TakeAcceptEnum } from "../funcs/screenshotsTake.js";

export class Screenshots extends ClientSDK {
  /**
   * Generate optimized website screenshot
   *
   * @remarks
   * Captures high-quality screenshots of websites with advanced optimization features including smart caching, CDN integration, request deduplication, and quota management. Supports multiple image formats (JPEG, PNG, WebP) with customizable dimensions, device emulation, and viewport settings. Implements efficient S3 streaming for large images and conditional requests for optimal performance.
   */
  async take(
    request: operations.TakeScreenshotRequest,
    options?: RequestOptions & { acceptHeaderOverride?: TakeAcceptEnum },
  ): Promise<operations.TakeScreenshotResponse | undefined> {
    return unwrapAsync(screenshotsTake(
      this,
      request,
      options,
    ));
  }
}
