/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Output image format. JPEG offers smaller file sizes, PNG supports transparency, WebP provides modern compression.
 */
export const Format = {
  Jpeg: "jpeg",
  Png: "png",
  Webp: "webp",
} as const;
/**
 * Output image format. JPEG offers smaller file sizes, PNG supports transparency, WebP provides modern compression.
 */
export type Format = ClosedEnum<typeof Format>;

/**
 * Types of web resources that can be blocked during screenshot capture
 */
export const BlockResource = {
  Document: "document",
  Stylesheet: "stylesheet",
  Image: "image",
  Media: "media",
  Font: "font",
  Script: "script",
  Texttrack: "texttrack",
  Xhr: "xhr",
  Fetch: "fetch",
  Prefetch: "prefetch",
  Eventsource: "eventsource",
  Websocket: "websocket",
  Manifest: "manifest",
  Signedexchange: "signedexchange",
  Ping: "ping",
  Cspviolationreport: "cspviolationreport",
  Preflight: "preflight",
  Other: "other",
} as const;
/**
 * Types of web resources that can be blocked during screenshot capture
 */
export type BlockResource = ClosedEnum<typeof BlockResource>;

/**
 * Set the preferred color scheme for websites that support dark/light mode theming
 */
export const PrefersColorScheme = {
  Light: "light",
  Dark: "dark",
} as const;
/**
 * Set the preferred color scheme for websites that support dark/light mode theming
 */
export type PrefersColorScheme = ClosedEnum<typeof PrefersColorScheme>;

/**
 * Accessibility setting to reduce animations and transitions for motion-sensitive users
 */
export const PrefersReducedMotion = {
  NoPreference: "no-preference",
  Reduce: "reduce",
} as const;
/**
 * Accessibility setting to reduce animations and transitions for motion-sensitive users
 */
export type PrefersReducedMotion = ClosedEnum<typeof PrefersReducedMotion>;

export type GetV1ScreenshotsTakeRequest = {
  apiKey: string;
  url: string;
  selector?: string | null | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  isMobile?: boolean | null | undefined;
  isLandscape?: boolean | null | undefined;
  hasTouch?: boolean | null | undefined;
  deviceScaleFactor?: number | null | undefined;
  /**
   * Output image format. JPEG offers smaller file sizes, PNG supports transparency, WebP provides modern compression.
   */
  format?: Format | undefined;
  quality?: number | undefined;
  blockAds?: boolean | null | undefined;
  blockCookieBanners?: boolean | null | undefined;
  blockTrackers?: boolean | null | undefined;
  blockRequests?: string | undefined;
  blockResources?: Array<BlockResource> | undefined;
  /**
   * Set the preferred color scheme for websites that support dark/light mode theming
   */
  prefersColorScheme?: PrefersColorScheme | undefined;
  /**
   * Accessibility setting to reduce animations and transitions for motion-sensitive users
   */
  prefersReducedMotion?: PrefersReducedMotion | undefined;
  isCached?: boolean | null | undefined;
  cacheTtl?: number | undefined;
  cacheKey?: string | undefined;
  headers?: string | undefined;
  cookies?: string | undefined;
  bypassCsp?: boolean | null | undefined;
};

export type GetV1ScreenshotsTakeResponse =
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>;

/** @internal */
export const Format$inboundSchema: z.ZodNativeEnum<typeof Format> = z
  .nativeEnum(Format);

/** @internal */
export const Format$outboundSchema: z.ZodNativeEnum<typeof Format> =
  Format$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Format$ {
  /** @deprecated use `Format$inboundSchema` instead. */
  export const inboundSchema = Format$inboundSchema;
  /** @deprecated use `Format$outboundSchema` instead. */
  export const outboundSchema = Format$outboundSchema;
}

/** @internal */
export const BlockResource$inboundSchema: z.ZodNativeEnum<
  typeof BlockResource
> = z.nativeEnum(BlockResource);

/** @internal */
export const BlockResource$outboundSchema: z.ZodNativeEnum<
  typeof BlockResource
> = BlockResource$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BlockResource$ {
  /** @deprecated use `BlockResource$inboundSchema` instead. */
  export const inboundSchema = BlockResource$inboundSchema;
  /** @deprecated use `BlockResource$outboundSchema` instead. */
  export const outboundSchema = BlockResource$outboundSchema;
}

/** @internal */
export const PrefersColorScheme$inboundSchema: z.ZodNativeEnum<
  typeof PrefersColorScheme
> = z.nativeEnum(PrefersColorScheme);

/** @internal */
export const PrefersColorScheme$outboundSchema: z.ZodNativeEnum<
  typeof PrefersColorScheme
> = PrefersColorScheme$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PrefersColorScheme$ {
  /** @deprecated use `PrefersColorScheme$inboundSchema` instead. */
  export const inboundSchema = PrefersColorScheme$inboundSchema;
  /** @deprecated use `PrefersColorScheme$outboundSchema` instead. */
  export const outboundSchema = PrefersColorScheme$outboundSchema;
}

/** @internal */
export const PrefersReducedMotion$inboundSchema: z.ZodNativeEnum<
  typeof PrefersReducedMotion
> = z.nativeEnum(PrefersReducedMotion);

/** @internal */
export const PrefersReducedMotion$outboundSchema: z.ZodNativeEnum<
  typeof PrefersReducedMotion
> = PrefersReducedMotion$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PrefersReducedMotion$ {
  /** @deprecated use `PrefersReducedMotion$inboundSchema` instead. */
  export const inboundSchema = PrefersReducedMotion$inboundSchema;
  /** @deprecated use `PrefersReducedMotion$outboundSchema` instead. */
  export const outboundSchema = PrefersReducedMotion$outboundSchema;
}

/** @internal */
export const GetV1ScreenshotsTakeRequest$inboundSchema: z.ZodType<
  GetV1ScreenshotsTakeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key: z.string(),
  url: z.string(),
  selector: z.nullable(z.string()).optional(),
  width: z.nullable(z.number().default(1920)),
  height: z.nullable(z.number().default(1080)),
  is_mobile: z.nullable(z.boolean().default(false)),
  is_landscape: z.nullable(z.boolean().default(false)),
  has_touch: z.nullable(z.boolean().default(false)),
  device_scale_factor: z.nullable(z.number().default(1)),
  format: Format$inboundSchema.default("jpeg"),
  quality: z.number().default(80),
  block_ads: z.nullable(z.boolean().default(false)),
  block_cookie_banners: z.nullable(z.boolean().default(false)),
  block_trackers: z.nullable(z.boolean().default(false)),
  block_requests: z.string().optional(),
  block_resources: z.array(BlockResource$inboundSchema).optional(),
  prefers_color_scheme: PrefersColorScheme$inboundSchema.default("light"),
  prefers_reduced_motion: PrefersReducedMotion$inboundSchema.default(
    "no-preference",
  ),
  is_cached: z.nullable(z.boolean().default(false)),
  cache_ttl: z.number().default(3600),
  cache_key: z.string().optional(),
  headers: z.string().optional(),
  cookies: z.string().optional(),
  bypass_csp: z.nullable(z.boolean().default(false)),
}).transform((v) => {
  return remap$(v, {
    "api_key": "apiKey",
    "is_mobile": "isMobile",
    "is_landscape": "isLandscape",
    "has_touch": "hasTouch",
    "device_scale_factor": "deviceScaleFactor",
    "block_ads": "blockAds",
    "block_cookie_banners": "blockCookieBanners",
    "block_trackers": "blockTrackers",
    "block_requests": "blockRequests",
    "block_resources": "blockResources",
    "prefers_color_scheme": "prefersColorScheme",
    "prefers_reduced_motion": "prefersReducedMotion",
    "is_cached": "isCached",
    "cache_ttl": "cacheTtl",
    "cache_key": "cacheKey",
    "bypass_csp": "bypassCsp",
  });
});

/** @internal */
export type GetV1ScreenshotsTakeRequest$Outbound = {
  api_key: string;
  url: string;
  selector?: string | null | undefined;
  width: number | null;
  height: number | null;
  is_mobile: boolean | null;
  is_landscape: boolean | null;
  has_touch: boolean | null;
  device_scale_factor: number | null;
  format: string;
  quality: number;
  block_ads: boolean | null;
  block_cookie_banners: boolean | null;
  block_trackers: boolean | null;
  block_requests?: string | undefined;
  block_resources?: Array<string> | undefined;
  prefers_color_scheme: string;
  prefers_reduced_motion: string;
  is_cached: boolean | null;
  cache_ttl: number;
  cache_key?: string | undefined;
  headers?: string | undefined;
  cookies?: string | undefined;
  bypass_csp: boolean | null;
};

/** @internal */
export const GetV1ScreenshotsTakeRequest$outboundSchema: z.ZodType<
  GetV1ScreenshotsTakeRequest$Outbound,
  z.ZodTypeDef,
  GetV1ScreenshotsTakeRequest
> = z.object({
  apiKey: z.string(),
  url: z.string(),
  selector: z.nullable(z.string()).optional(),
  width: z.nullable(z.number().default(1920)),
  height: z.nullable(z.number().default(1080)),
  isMobile: z.nullable(z.boolean().default(false)),
  isLandscape: z.nullable(z.boolean().default(false)),
  hasTouch: z.nullable(z.boolean().default(false)),
  deviceScaleFactor: z.nullable(z.number().default(1)),
  format: Format$outboundSchema.default("jpeg"),
  quality: z.number().default(80),
  blockAds: z.nullable(z.boolean().default(false)),
  blockCookieBanners: z.nullable(z.boolean().default(false)),
  blockTrackers: z.nullable(z.boolean().default(false)),
  blockRequests: z.string().optional(),
  blockResources: z.array(BlockResource$outboundSchema).optional(),
  prefersColorScheme: PrefersColorScheme$outboundSchema.default("light"),
  prefersReducedMotion: PrefersReducedMotion$outboundSchema.default(
    "no-preference",
  ),
  isCached: z.nullable(z.boolean().default(false)),
  cacheTtl: z.number().default(3600),
  cacheKey: z.string().optional(),
  headers: z.string().optional(),
  cookies: z.string().optional(),
  bypassCsp: z.nullable(z.boolean().default(false)),
}).transform((v) => {
  return remap$(v, {
    apiKey: "api_key",
    isMobile: "is_mobile",
    isLandscape: "is_landscape",
    hasTouch: "has_touch",
    deviceScaleFactor: "device_scale_factor",
    blockAds: "block_ads",
    blockCookieBanners: "block_cookie_banners",
    blockTrackers: "block_trackers",
    blockRequests: "block_requests",
    blockResources: "block_resources",
    prefersColorScheme: "prefers_color_scheme",
    prefersReducedMotion: "prefers_reduced_motion",
    isCached: "is_cached",
    cacheTtl: "cache_ttl",
    cacheKey: "cache_key",
    bypassCsp: "bypass_csp",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1ScreenshotsTakeRequest$ {
  /** @deprecated use `GetV1ScreenshotsTakeRequest$inboundSchema` instead. */
  export const inboundSchema = GetV1ScreenshotsTakeRequest$inboundSchema;
  /** @deprecated use `GetV1ScreenshotsTakeRequest$outboundSchema` instead. */
  export const outboundSchema = GetV1ScreenshotsTakeRequest$outboundSchema;
  /** @deprecated use `GetV1ScreenshotsTakeRequest$Outbound` instead. */
  export type Outbound = GetV1ScreenshotsTakeRequest$Outbound;
}

export function getV1ScreenshotsTakeRequestToJSON(
  getV1ScreenshotsTakeRequest: GetV1ScreenshotsTakeRequest,
): string {
  return JSON.stringify(
    GetV1ScreenshotsTakeRequest$outboundSchema.parse(
      getV1ScreenshotsTakeRequest,
    ),
  );
}

export function getV1ScreenshotsTakeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ScreenshotsTakeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ScreenshotsTakeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ScreenshotsTakeRequest' from JSON`,
  );
}

/** @internal */
export const GetV1ScreenshotsTakeResponse$inboundSchema: z.ZodType<
  GetV1ScreenshotsTakeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>),
  z.instanceof(ReadableStream<Uint8Array>),
  z.instanceof(ReadableStream<Uint8Array>),
]);

/** @internal */
export type GetV1ScreenshotsTakeResponse$Outbound =
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>;

/** @internal */
export const GetV1ScreenshotsTakeResponse$outboundSchema: z.ZodType<
  GetV1ScreenshotsTakeResponse$Outbound,
  z.ZodTypeDef,
  GetV1ScreenshotsTakeResponse
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>),
  z.instanceof(ReadableStream<Uint8Array>),
  z.instanceof(ReadableStream<Uint8Array>),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1ScreenshotsTakeResponse$ {
  /** @deprecated use `GetV1ScreenshotsTakeResponse$inboundSchema` instead. */
  export const inboundSchema = GetV1ScreenshotsTakeResponse$inboundSchema;
  /** @deprecated use `GetV1ScreenshotsTakeResponse$outboundSchema` instead. */
  export const outboundSchema = GetV1ScreenshotsTakeResponse$outboundSchema;
  /** @deprecated use `GetV1ScreenshotsTakeResponse$Outbound` instead. */
  export type Outbound = GetV1ScreenshotsTakeResponse$Outbound;
}

export function getV1ScreenshotsTakeResponseToJSON(
  getV1ScreenshotsTakeResponse: GetV1ScreenshotsTakeResponse,
): string {
  return JSON.stringify(
    GetV1ScreenshotsTakeResponse$outboundSchema.parse(
      getV1ScreenshotsTakeResponse,
    ),
  );
}

export function getV1ScreenshotsTakeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ScreenshotsTakeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ScreenshotsTakeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ScreenshotsTakeResponse' from JSON`,
  );
}
